FROM hicn-vpp/base
MAINTAINER s.rene@ucl.ac.uk

COPY startup_router1.conf /tmp/startup_init.conf
COPY startvpp_router1.sh /
#COPY startup1.conf /etc/vpp/startup1.conf

ENTRYPOINT /startvpp_router1.sh
